### ISSUE TITLE
TA Review (SRS): Traceability Fixes

### ISSUE THREAD

**Issue by SammyG7** [SammyG7/Mac-AR#100]
**Summary**
The following feedback should be implemented:
- [x] Traceability information should be included with each individual requirement
- [x] Traceability should exist between use cases and requirements

**Deadline**
Jan 8th, 2024

**Estimated Work Hours**
0.5 Hours

**Comment by kierangara** [comment]
Resolved with commit 8cb63066fe0badad727af5e896be3deea98e11d2
