### ISSUE TITLE
TA Review (SRS): Unclear Requirements 

### ISSUE THREAD

**Issue by SammyG7** [SammyG7/Mac-AR#101]
**Summary**
Fix up unclear and redundant requirements:
- [x] Ambiguous use of the word user. Use case diagram, ST1, and ST3 have conflicting uses of the word
- [x] "Settings" in section 2.2.3 unclear
- [x] ER2 and ER3 should be more specific that a user left, or specify that they are predicated on ER1
- [x] SG1 seems redundant based on SG2
- [x] SG2 could be reworded to include pausing to replace SG3
- [x] SG3 seems redundant
- [x] DS3 seems redundant
- [x] PR2 is infeasible based on the current wording (Having a server running 24/7)
- [x] UH1 and OE1 contradict each other
- [x] Unclear what "Run" means in UH1
- [x] Unclear what "Publicly accessed" means in SR1

**Deadline**
Jan 8th, 2024

**Estimated Work Hours**
2 Hours

**Comment by kierangara** [comment]
Completed in commit id: 9a79228b09733150d9d879f807a2f0d5e8809acc  
Settings in 2.2.3 unclear update transferred to #97
