### ISSUE TITLE
TA Review (SRS): Fix Fit Criterion

### ISSUE THREAD

**Issue by SammyG7** [SammyG7/Mac-AR#103]
**Summary**
The following feedback should be implemented:
- [x] Fit criterion for MS2 inadequate  
- [x] Fit criterion missing for CR1, LR1
- [x] Lot's of redundant rationale for requirements, or information that should just be included in the requirements itself (Ex. JG4)
- [x] Rationale could be added to SR2

**Deadline**
Jan 8th, 2023

**Estimated Work Hours**
1 hour

**Comment by kierangara** [comment]
Resolved with commits 3de0e651989dadceab6873d6cd86ff4da9c1fe73 and 6130a300bdadaddacc7561825ea496b8ce966312
