### ISSUE TITLE
TA Review (SRS): Missing Requirements/ Information

### ISSUE THREAD

**Issue by SammyG7** [SammyG7/Mac-AR#104]
**Summary**
Some useful requirements are missing:
- [x] No requirements for trying to join a full room
- [x] No details on allowed room names, room sizes, etc.
- [x] No Phase-In information given
- [x] No information related to the specifics of the puzzles

**Deadline**
Jan 8th, 2024

**Estimated Work Hours**
1 Hour

**Comment by kierangara** [comment]
Resolved with 1bc2310c2ceaa427d07daa54067159177351fea6 and 73b52daf441b1946cc5c31429a13ddaa2b782092

**Comment by kierangara** [comment]
Current implementation does not require limitation of game room name as this is not necessary for the study. This may be a future change if the game were to be more widely publicized to prevent inappropriate names.
