### ISSUE TITLE
TA Review (HA): Implement Grammar

### ISSUE THREAD

**Issue by SammyG7** [SammyG7/Mac-AR#106]
**Summary**
The following feedback should be implemented:

- [x] Each cause should have its own label
- [x] Definition of hazards should be more specific
- [x] Some failures are just restating failure modes (Ex H4-2)
- [x] Each cause should have its own recommended action and requirement. Reuse should refer to its first appearance (Ex. H1-2a)
- [x] No hazards related to saving user data
- [x] The second recommended action seems to be saying two things, since the user disconnecting is the cause of the hazard in the first place

**Deadline**
Jan 8th, 2024

**Estimated Work Hours**
2 Hours

**Comment by ethanlucask** [comment]
HA updated to fix all TA feedback. In response to the "No hazards related to saving user data", the scope of the project changed and so no user data is being saved.

**Comment by ethanlucask** [comment]
Completed in commit ID: 071fe99b40d19bf45277384b4a737ea5530ae219
