### ISSUE TITLE
Supervisor Meeting 2

### ISSUE THREAD

**Issue by ethanlucask** [SammyG7/Mac-AR#11]
September 26, 2023

Dr. Yuan, Matthew, Sam, Ethan

Agenda:
- Update Dr. Yuan on current progress
- Discuss implementation ideas

**Comment by ethanlucask** [comment]
Associated Meeting Minutes: https://github.com/SammyG7/Mac-AR/blob/main/docs/MeetingMinutes/MeetingMinutes.pdf

**Comment by kierangara** [comment]
Missed due to illness.
