### ISSUE TITLE
Update SRS and VnV traceabilty matrices - Once all other updates complete

### ISSUE THREAD

**Issue by kierangara** [SammyG7/Mac-AR#110]
**Documents**:
SRS, VnV Plan
**Changes**:
Update both traceability matrices to match updates based on feedback once all updates complete.
**Checklists**:
- [ ] Update SRS traceability matrix
- [ ] Update VnV Plan traceability matrix

**Due Date:**
Feb 5, 2024

**Comment by MatthewCollard** [comment]
Completed in commit id: fd684242dc1584248227078c482b651bbb1c9a8c
