### ISSUE TITLE
Team 2 Review (MIS): Access Routine output not defined in MIS.

### ISSUE THREAD

**Issue by Haxerus** [SammyG7/Mac-AR#119]
@samm82
Name: Team 2 Review
About: Access Routine Semantics Output

**Summary**
The JoinAsync function is stated to have no output in the Exported Access Program table.
![image](https://github.com/SammyG7/Mac-AR/assets/12162897/cf6147bd-ac63-45d6-a662-7b58cfeeafca)

However, in the access routine semantics section, the output is stated to be "**out := isJoining**"
![image](https://github.com/SammyG7/Mac-AR/assets/12162897/5de77d9b-9260-4c98-9865-2a0c9fd86393)

"isJoining" is not defined anywhere else so it is unclear what this output means. isJoining should either be defined elsewhere or removed.

**Deadline**
- March 1, 2024

**Estimated Work Hours**
- ~1 hr

**Comment by kierangara** [comment]
Resolved with commit feb7ed5bc04944bfd083876d0fd64f73e065ace4
