### ISSUE TITLE
Team 2 Review (MG): Database Module should use Hardware hiding Module

### ISSUE THREAD

**Issue by qw33ha** [SammyG7/Mac-AR#120]
@samm82
Name: Team 2 Review
About: Database Module should use Hardware hiding Module

Summary
The database module should also be using Hardware hiding module since it will in the end be using some kind of hardware of the device.
<img width="680" alt="Screen Shot 2024-01-19 at 11 37 59 PM" src="https://github.com/SammyG7/Mac-AR/assets/83600619/269bee45-4564-42bb-9b67-7b3c17a7bebf">

Deadline: March 1st

Estimated Work Hours: 0.5hr

**Comment by ethanlucask** [comment]
Not an issue. Layout of these modules is fine as is. Database is not needed to be connected to hardware
