### ISSUE TITLE
Team 2 Review (MIS): Environment Variables lacking details

### ISSUE THREAD

**Issue by Haxerus** [SammyG7/Mac-AR#121]
@samm82
Name: Team 2 Review
About: The Environment Variables sections in the MIS is not descriptive enough. They are lacking details such as type.

**Summary**
The environment variables section lacks descriptiveness. Environment Variables should have their type specified like any other variable. For example, in the TA follow-up, they mentioned that a Device Screen could have the type of a "2D Array of Pixels". Similarly, a device keyboard could be a 2D array of characters.
![image](https://github.com/SammyG7/Mac-AR/assets/12162897/945fa0ad-c021-49f6-bad1-4bd06f30d666)
(example in figure taken from Text Communication Module)

**Deadline**
- March 1, 2024

**Estimated Work Hours**
~3 hrs

**Comment by SammyG7** [comment]
Updated environment variables to be formatted the same as other variables

**Comment by SammyG7** [comment]
Updated in #310
