### ISSUE TITLE
Team 2 Review (MG): Documentation Module

### ISSUE THREAD

**Issue by qw33ha** [SammyG7/Mac-AR#122]
@samm82
Name: Team 2 Review
About: Documentation Module

Summary
Documentation Module should not be a module if that cannot be categorized as an ADT/Library/Record. As in the rubric, a module is described as a work assignment for a programmer to work on. I suggest removing this module and adding this 'mapping' somewhere else as it cannot fit in the DGA graph as well.
<img width="684" alt="Screen Shot 2024-01-19 at 11 42 55 PM" src="https://github.com/SammyG7/Mac-AR/assets/83600619/135c8f18-2479-4029-aa44-42344634dbf1">

Deadline: March 1st

Estimated Work Hours: 0.25hr

**Comment by ethanlucask** [comment]
It was suggested by the TA to have a Documentation module for traceability. So this is not an issue.
