### ISSUE TITLE
Team #2 Review (MIS): Inconsistency between MIS use and MG graph

### ISSUE THREAD

**Issue by qw33ha** [SammyG7/Mac-AR#123]
@samm82
Name: Team 2 Review
About: Inconsistency between MIS use and MG graph

Summary
The module hierarchy graph in the module guide says M2, M3, M4, M5 and M5 should be using the Database Module and Error Manager Module, but in MIS only M6 (multi-user puzzle) has Error Manager in its Uses. Not sure if the graph is misinterpreted or there are missing uses in MIS.

<img width="634" alt="Screen Shot 2024-01-19 at 11 50 24 PM" src="https://github.com/SammyG7/Mac-AR/assets/83600619/f2d57a74-d5c3-4953-a540-9598c0842164">
<img width="403" alt="Screen Shot 2024-01-19 at 11 50 39 PM" src="https://github.com/SammyG7/Mac-AR/assets/83600619/f4ffe318-d0c9-4d55-be8d-47283dafd9f5">
<img width="658" alt="Screen Shot 2024-01-19 at 11 50 51 PM" src="https://github.com/SammyG7/Mac-AR/assets/83600619/c4791e6b-06c7-4584-854d-04172c84a840">
<img width="705" alt="Screen Shot 2024-01-19 at 11 52 06 PM" src="https://github.com/SammyG7/Mac-AR/assets/83600619/80cfbe50-515c-4ccb-b764-187c35a90d2c">
<img width="544" alt="Screen Shot 2024-01-19 at 11 51 15 PM" src="https://github.com/SammyG7/Mac-AR/assets/83600619/5240d85d-949e-4075-a1c2-81245e2b72a2">

Deadline: March 1st

Estimated Work Hours: 0.5hr

**Comment by SammyG7** [comment]
Updated module uses in MIS to match graph

**Comment by SammyG7** [comment]
Updated in #310
