### ISSUE TITLE
Team 2 Review (MIS): Access Routine Output Mismatch

### ISSUE THREAD

**Issue by beatlepie** [SammyG7/Mac-AR#124]
@samm82
Name: Team 2 Review
About: Access Routine Semantics Output Mismatch

**Summary**
![image](https://github.com/SammyG7/Mac-AR/assets/46289372/260bae08-5202-4608-9a6a-d73cbc868d6a)
![image](https://github.com/SammyG7/Mac-AR/assets/46289372/4aee3d26-6f4a-4baf-a1ce-bd39a275033f)
The output of this function is defined differently in the above sections.
**Deadline**
March 1, 2024

**Estimated Work Hours**
~30 min

**Comment by kierangara** [comment]
Resolved with commit feb7ed5bc04944bfd083876d0fd64f73e065ace4
