### ISSUE TITLE
Team 2 Review (MIS): Semantics for HandleClientDisconnected() in MIS of Database/Network Manager Module

### ISSUE THREAD

**Issue by millem42** [SammyG7/Mac-AR#125]
@samm82
Name: Team 2 Review
About: Semantics for HandleClientDisconnected() in MIS of Database/Network Manager Module

**Summary**
In the Access Routine Semantics section of the MIS of the Database/Network Manager Module, the syntax is incorrect for the HandleClientDisconnected() method. The value of "i" should be specified again when calling the players.RemoveAt(i) method (e.g. the value of i where players[i].clientId == clientId).
![image](https://github.com/SammyG7/Mac-AR/assets/98553968/f9f8453c-764c-4909-af9d-ce57ed1af8d6)

**Deadline**
March 1st

**Estimated Work Hours**
15 mins

**Comment by SammyG7** [comment]
I think there might be a misunderstanding with what the statement represents. Updated the syntax to hopefully be more clear

**Comment by SammyG7** [comment]
Updated in #310
