### ISSUE TITLE
Team 2 Review (MIS): Simon Says Puzzle Module missing state variables.

### ISSUE THREAD

**Issue by Haxerus** [SammyG7/Mac-AR#126]
@samm82
Name: Team 2 Review
About: Missing state variables in MIS for Simon Says Module.

**Summary**
The Simon Says Puzzle Module has no state variables but the access routine section implies that it should. The variables are instead placed in the local variables section which is not appropriate.

Local variables should only be used for specification purposes to designs simpler and are not available at runtime as indicated in the provided MIS Format document.

![image](https://github.com/SammyG7/Mac-AR/assets/12162897/a5a19584-2a3e-4928-bc0f-84c43a9006c4)

The module contains several routines which interact with the state of the module, as is clearly shown in the transition sections. 

![image](https://github.com/SammyG7/Mac-AR/assets/12162897/c6299291-0bef-459b-ad5b-6d46478d78ee)

Solution: The variables declared in the local variables should be moved to the state variables.

**Deadline**
March 1, 2024

**Estimated Work Hours**
~3 hrs

**Comment by SammyG7** [comment]
The Simon Says module has been updated to include the required state variables

**Comment by SammyG7** [comment]
Updated in #310
