### ISSUE TITLE
Team 2 Review (MIS) : Potential updates to Database/Network Manager Module

### ISSUE THREAD

**Issue by abh1nh** [SammyG7/Mac-AR#127]
@samm82

**Summary**:
![image](https://github.com/SammyG7/Mac-AR/assets/93843390/0a81e81f-733f-4c88-849c-0d8b200cb27c)

Some of the functions in the Database/Network Manager module can be updated to output a boolean value to ensure that the player connects / disconnects proceed as expected.

It also seems to be possible to get database related errors such as connection errors in the functions, while the exception section is empty.

**Deadline**: March 1st

**Estimated Work Hours** : 1 hour

**Comment by SammyG7** [comment]
These values can't be updated since they are the result of built in unity frameworks. Updated the description of the module in the MIS to explicitly state this.

**Comment by SammyG7** [comment]
Updated in #310
