### ISSUE TITLE
Team 2 Review (MIS): Variable Accessibility

### ISSUE THREAD

**Issue by beatlepie** [SammyG7/Mac-AR#128]
@samm82
Name: Team 2 Review
About: Variable Accessibility

**Summary**
![image](https://github.com/SammyG7/Mac-AR/assets/46289372/31a2dfdc-8e61-4fc4-b7b3-0f2666c20027)
The comboSet variable is not defined in local or state variable, but it is somehow being used. This seems to be a state variable for the module.
**Deadline**
March 1, 2024

**Estimated Work Hours**
1 hour

**Comment by kierangara** [comment]
Resolved with commit 4e146b85e44982f56e6f90b2af7086249ebafdee
