### ISSUE TITLE
Team 18 Review (MIS): The semantics are unclear for the access program

### ISSUE THREAD

**Issue by jiaoa3** [SammyG7/Mac-AR#129]
@CSchank 

**Summary**
The semantics are unclear for the access program in the Game Room Module. 
Including inconsistent naming and unmatching output.

![1](https://github.com/SammyG7/Mac-AR/assets/77683292/602c7758-3061-4a71-8bf6-207a15f35097)
![2](https://github.com/SammyG7/Mac-AR/assets/77683292/44199bd2-b584-4175-afe6-9b2ec682b427)

**Deadline**
March 1st
**Estimated Work Hours**
10mins

**Comment by kierangara** [comment]
Resolved with 9a662ae2eb2a085651ee25fb0ca314bdce84bfeb
