### ISSUE TITLE
Team # 18 Review (MIS): Format Inconsistency

### ISSUE THREAD

**Issue by marischan888** [SammyG7/Mac-AR#130]
@CSchank 

**Summary**
Some of the transition parts in 12.4.4 (MIS) do not contain the close brackets.
<img width="613" alt="Screenshot 2024-01-21 at 17 53 46" src="https://github.com/SammyG7/Mac-AR/assets/77364176/b1ffd4b1-9b13-4905-ae1f-d51c523ab670">

**Deadline**
March 1st

**Estimated Work Hours**
10 mins

**Comment by kierangara** [comment]
Resolved with commit 4bf8cf3424c140996da558b98083b8c52daa2f1a
