### ISSUE TITLE
Team 18 Review (MIS): Miss use of assignment operator

### ISSUE THREAD

**Issue by yex33** [SammyG7/Mac-AR#131]
@CSchank 

**Summary**
The notation of the assignment operator := is described in the notation section as
![image](https://github.com/SammyG7/Mac-AR/assets/74110776/65ff0a39-cb2b-49ed-b0f0-83c10b76f0e8)

However, in some MIS sections, the assignment operator is used to specify the type of the variable instead of describing an assignment of value.
![image](https://github.com/SammyG7/Mac-AR/assets/74110776/8509b8df-ddf1-4193-9a1d-b50e836e3b9b)

**Deadline**
March 1st, 2024

**Estimated Work Hours**
10 min

**Comment by kierangara** [comment]
Resolved with 6c918f09c33e8657ef471cd8604ed64ed382f0b2
