### ISSUE TITLE
Team 18 Review (MIS): Variable used in function is not defined

### ISSUE THREAD

**Issue by qstommyshu** [SammyG7/Mac-AR#132]
@CSchank 

**Summary**
The variable Lobbies used under the RefreshList() function in Game Room Module is not defined. This variable should be included as a state variable or an input parameters.
<img width="530" alt="image" src="https://github.com/SammyG7/Mac-AR/assets/56746466/8be8d73e-d324-4b90-b45d-a00a4d36d264">

<img width="818" alt="image" src="https://github.com/SammyG7/Mac-AR/assets/56746466/aa68fbf9-bba6-4a02-bf70-11585f2757ed">

**Deadline**
March 1st

**Estimated Work Hours**
1 hour

**Comment by kierangara** [comment]
Resolved with 9a662ae2eb2a085651ee25fb0ca314bdce84bfeb
