### ISSUE TITLE
Team 18 Review (MIS): Use Hierarchy Diagram 

### ISSUE THREAD

**Issue by KehaoHuang** [SammyG7/Mac-AR#133]
@CSchank 

According to [Parnas (1978)](chrome-extension://efaidnbmnnnibpcajpcglclefindmkaj/https://courses.cs.washington.edu/courses/cse503/08wi/parnas-1979.pdf), each level of the hierarchy offers a testable and usable subset of the system, and modules in the higher level of the hierarchy are essentially simpler because they use modules from the lower levels. Your team's use hierarchy is currently not organized in such a hierarchical way. 

In addition, some connections between modules seem to have a wrong direction. In your team's use hierarchy,  the multiplayer puzzle module is pointed by all the other puzzle modules. However, in your MIS you said the multiplayer puzzle module is the base module that all other puzzle modules will inherit from. According to [Parnas (1978)](chrome-extension://efaidnbmnnnibpcajpcglclefindmkaj/https://courses.cs.washington.edu/courses/cse503/08wi/parnas-1979.pdf), programs A and B that A uses B if correct execution of B may be necessary for A to complete the task described in its specification. That is, A uses B if there exist situations in which the correct functioning of A depends upon the availability of a correct implementation of B.

![Use Hierarchy](https://github.com/SammyG7/Mac-AR/assets/77684152/a8ff552c-36cb-40dc-a001-33b27f837bbc)

**Comment by SammyG7** [comment]
The diagram as is correctly conveys the information we are trying to get across. For now we will leave as is
