### ISSUE TITLE
Team 18 Review (MIS): Module not included in the Use Hierarchy Diagram

### ISSUE THREAD

**Issue by qstommyshu** [SammyG7/Mac-AR#134]
@CSchank 

**Summary**
Here is the Use Hierarchy Diagram:
<img width="390" alt="image" src="https://github.com/SammyG7/Mac-AR/assets/56746466/4b547c98-2c89-4590-b460-834ad135c273">

Here is the definition of the Documentation Module:
<img width="543" alt="image" src="https://github.com/SammyG7/Mac-AR/assets/56746466/496d2773-9236-4960-98e7-0ff7a314ed6a">

The documentation module should either be removed or added to the Use Hierarchy Diagram as all modules should be on the Use Hierarchy Diagram.

**Deadline**
March 1st

**Estimated Work Hours**
1 hour

**Comment by SammyG7** [comment]
As discussed with the TA prior to Rev 0, the documentation module was intentionally left out of the diagram. Will leave as is
