### ISSUE TITLE
TA review : VNV

### ISSUE THREAD

**Issue by MatthewCollard** [SammyG7/Mac-AR#170]
@samm82

**Summary**

- [x] When referencing another section, you should include a link to it. Your usability survey is never referenced by a requirement!
- [x] Minor grammar issues. Test-SG10 should be removed, since it is just Test-SG9 with a different ID number. 
- [x] You mention Dr. Irene Yuan is an "SRS verifier", but state that she will be able to "Validate documentation"; make sure you are using terminology consistently, since "verification" and "validation" are two different things!
- [x] #174
- [x] #176
- [x] #177
- [x] #178
- [x] #179
- [x] #181
- [x] Test-SG2's method is unclear: it currently seems to say "if the tester pauses the game, the tester should be able to continue doing actions", where the derivation implies that the italicized part should be "other group members". 
- [x] Since Test-SG5 is built with "the limit imposed by Unity" in mind, it isn't really a test of "the extreme case", since the user will likely be unaware of this. 
- [x] #183
- [x] #185
- [x] #182
- [x] #180
- [x] While there are issues with their tests in #113, the two are slightly different, testing different "levels" of installability.

**Deadline**

March 20th, 2024

**Estimated Work Hours**

6 hours

**Comment by MatthewCollard** [comment]
Task 1 completed in commit id: c5db539b20c58f8f7c266343d3105fd00122f56d

**Comment by kierangara** [comment]
All tasks completed.
