### ISSUE TITLE
TA Review(VNV) Specify testing inputs

### ISSUE THREAD

**Issue by SammyG7** [SammyG7/Mac-AR#176]

**Comment by MatthewCollard** [comment]
Note that for test cases to be specific, the actual data should be included as part of the tests; you could even make a table to easily define multiple tests with different inputs! For example, for any testing of passwords, you should specify what password(s) should be used in the test (and why).

**Comment by MatthewCollard** [comment]
Resolved in 32022ff0d73a08ca81ef28b576512481ea47ff8c
