### ISSUE TITLE
Fix capacity references in SRS and VnV

### ISSUE THREAD

**Issue by MatthewCollard** [SammyG7/Mac-AR#181]
Test-JR1 seems to imply that only rooms with available capacity will be displayed to the user; this should be made explicit in your SRS (could be done by changing JG5; my feedback on this may have been built on a wrong assumption) and have a separate test case to ensure that no room that is at/over capacity is displayed to the user. What if the capacity of a room is reduced to below its current capacity (e.g., a room with 5 people currently in it is edited to have a capacity of 3)? This should also be reflected in your SRS.

**Comment by kierangara** [comment]
Closed with commit 9b46e735ad55b0116028201aa2a81a4425708a3d
