### ISSUE TITLE
Missing Traceability

### ISSUE THREAD

**Issue by MatthewCollard** [SammyG7/Mac-AR#183]
Some traceability is incorrect or missing: Test-SG5 doesn't really test SG7, but Test-SG8 also seems to test LG1 and Test-PI4 seems to test PI4. Test-CR2 to Test-CR6 all seem to test CG5 as well (because of this, Test-CR7 seems redundant). Test-PI7 and Test-PI8 seem to test the same thing with little/no difference.

**Comment by SammyG7** [comment]
Updated traceability, redundant test cases removed
