### ISSUE TITLE
Team 18  SRS Review: Missing “Business Data Model & Data Dictionary” without explanation

### ISSUE THREAD

**Issue by jiaoa3** [SammyG7/Mac-AR#21]
![image](https://github.com/SammyG7/Mac-AR/assets/77683292/b17436a5-60c8-48a2-a3bd-1f8c14661bfa)

Prior to heading "Project Drivers", the Volere template (Robertson and Robertson, 2012) was mentioned. However, we didn't find the section "Business Data Model & Data Dictionary", and no explanation for why this section was omitted from the template.

@CSchank

**Comment by kierangara** [comment]
Issue is not relevant to the instance of the Volere template used, but statement of modifications to template added in commit be256a71bd8c1fd87d7bee3858d9c4fa714978eb
