### ISSUE TITLE
Puzzle flow update

### ISSUE THREAD

**Issue by kierangara** [SammyG7/Mac-AR#215]
**Due Date**
Mar 24
**Priority**
High/ Medium/ Low
High
**Description**
Implement the idea to make the puzzle flow better/ have better story and use AR more.

- Show multiple puzzles at once. Keypad activates wires, activates simon says, brings up maze which brings up green puzzle.

**Associated Requirement***
N/A

**Comment by SammyG7** [comment]
Added in PR #250
