### ISSUE TITLE
Team 18 SRS Review: Inappropriate content in SRS

### ISSUE THREAD

**Issue by jiaoa3** [SammyG7/Mac-AR#22]
![image](https://github.com/SammyG7/Mac-AR/assets/77683292/90ebb308-d985-419c-a745-c2159d650508)

The sentence "If you make further modifications to the template, you should explicitly state what modifications were made." seems to be inappropriate content in this SRS. It appears to be an instruction or guideline for document authors and maintainers rather than a part of the actual software requirements.

@CSchank

**Comment by ethanlucask** [comment]
Completed in commit ID: d9d136da73141de01d320198e16eb7254ec3ecda
