### ISSUE TITLE
Team #2 Review (VnV Report): TBD Tests

### ISSUE THREAD

**Issue by qw33ha** [SammyG7/Mac-AR#226]
@samm82

**Summary** Some of the tests (most of them in functional requirement evaluation)  does not have an actual output. There is no explanation why the tests are missing in the document, not sure if the the requirements are moved out of scope or the team just forgot to test.
![image](https://github.com/SammyG7/Mac-AR/assets/83600619/7f99d00a-5cbf-41aa-b27c-daa73eface81)

**Deadline** April 4th

**Estimated Work Hours** 5 hrs

**Comment by MatthewCollard** [comment]
Completed in commit id: [48154ac](https://github.com/SammyG7/Mac-AR/commit/48154ac548af3fd8a7509283565242cab2f1d720)
