### ISSUE TITLE
Team #2 Review (VnV Report): Missing Automated Test

### ISSUE THREAD

**Issue by qw33ha** [SammyG7/Mac-AR#227]
@samm82

**Summary** The automated tests running in the project only include 682 tests from 3rd party libraries, not the test 'the Mac-AR team has created'. 
![image](https://github.com/SammyG7/Mac-AR/assets/83600619/31b25598-9efc-4dbd-acce-661ae77b710f)
Also the unit test CI is not reporting the result of tests created by the team or the code coverage report. Not sure how the unit tests are conducted if the team is not using UTF
![image](https://github.com/SammyG7/Mac-AR/assets/83600619/5e2524bb-d050-4423-aa53-f7119e825b01)

**Deadline** April 4th

**Estimated Work Hours** 10 hrs

**Comment by MatthewCollard** [comment]
Our own branch of unit testing has not been pushed to main as of yet

**Comment by MatthewCollard** [comment]
We have automated tests with CI/CD on Github, as well as automated tests that we have to run manually on Unity.
