### ISSUE TITLE
Team 18 Review (VnV report): Test cases with TBD status

### ISSUE THREAD

**Issue by qstommyshu** [SammyG7/Mac-AR#228]
@CSchank 

**Summary**
There are many TBD status in test cases. However, there is no explanation why these tests are TBD, and what does TBD mean for test cases.

![image](https://github.com/SammyG7/Mac-AR/assets/56746466/9bf1b3cd-4adb-4f0f-b729-a26c55e707b9)

**Deadline**
April 4

**Estimated Work Hours**
1 hour

**Comment by MatthewCollard** [comment]
Completed in commit id: [48154ac](https://github.com/SammyG7/Mac-AR/commit/48154ac548af3fd8a7509283565242cab2f1d720)
