### ISSUE TITLE
Team 18 Review (VnV Report): Test Cases Lacking Specific Names

### ISSUE THREAD

**Issue by marischan888** [SammyG7/Mac-AR#229]
@CSchank 

**Summary**
It is necessary to provide specific details for each test case, as mentioned in the slide.
<img width="495" alt="Screenshot 2024-03-09 at 18 03 50" src="https://github.com/SammyG7/Mac-AR/assets/77364176/b0e00470-96dc-4749-9a5b-ff9ad9abc0db">

However, the Unit Testing section lacks inclusion of specific names for the test cases.
<img width="646" alt="Screenshot 2024-03-09 at 18 05 00" src="https://github.com/SammyG7/Mac-AR/assets/77364176/0a6e72c8-7cbf-497c-b2a3-018f7ea4f580">

**Deadline**
April 4th

**Estimated Work Hours**
1 hour

**Comment by MatthewCollard** [comment]
The specific names of these tests are in the VnVPlan document, which you can cross-reference with the Id
