### ISSUE TITLE
Team 18 SRS Review: Missing citation and clarification for external information “ARctic”

### ISSUE THREAD

**Issue by KehaoHuang** [SammyG7/Mac-AR#23]
The reference to the AR game called ARctic Escape in the Ready-Made Products section is not cited in the document. As mentioned in the SRS rubric, all appropriate external information should be incorporated into the document. It is essential to provide proper citations and references for external sources and products to ensure transparency, give credit to the creators, and allow readers to access additional information conveniently if needed. Therefore, it would be helpful to include a citation for the aforementioned product.

@CSchank

**Comment by ethanlucask** [comment]
Completed in commit ID: d9d136da73141de01d320198e16eb7254ec3ecda
