### ISSUE TITLE
Team 18 Review (VnV Report): missing one non-functional quality 

### ISSUE THREAD

**Issue by jiaoa3** [SammyG7/Mac-AR#230]
@CSchank 
![image](https://github.com/SammyG7/Mac-AR/assets/77683292/a7bb48be-c22d-4081-9326-ecc56af16086)
In the rubric, 2 non-functional qualities are expected, however there’s only one Usability Survey included in the VnVReport. 

**Deadline**
April 1
**Estimated Work Hours**
20mins

**Comment by MatthewCollard** [comment]
We have non functional quality in code coverage Metrics, and tests PR1-PR3
