### ISSUE TITLE
Team 18 Review (VnV Report): Formatting: list of figures not required

### ISSUE THREAD

**Issue by yex33** [SammyG7/Mac-AR#231]
@CSchank 

**Summary**
There is no figures throughout the document. The "List of Figures" section is empty and redundant.

**Deadline**
April 4th

**Estimated Work Hours**
2 min

**Comment by MatthewCollard** [comment]
Resolved in commit id: 82a9b4ec4dfe3751fcaa257d9e3d4cf4948dde69
