### ISSUE TITLE
Team #2 Review (VnV Report): Initial State Missing in Tests

### ISSUE THREAD

**Issue by millem42** [SammyG7/Mac-AR#232]
@samm82

**Summary**
The VnV Report does not include the initial states for any of the tests. Including the initial states will help readers further understand how the test was performed.

![image](https://github.com/SammyG7/Mac-AR/assets/98553968/9716ff07-1739-4a52-81b8-fa87c3f1fa71)

**Deadline**
April 4

**Estimated Work Hours**
2 hours

**Comment by MatthewCollard** [comment]
Initial states are listed in the VnvPlan, which you can cross reference with the Id. We didn't add it to the report to make the charts easier to read
