### ISSUE TITLE
Team #2 Review (VnVReport): Missing results from Non-Dynamic Tests in VnVPlan

### ISSUE THREAD

**Issue by Haxerus** [SammyG7/Mac-AR#233]
@samm82

**Summary**
The VnVReport is missing results for several non-dynamic tests planned in the VnVPlan. These primarily involved the verification of documentation. 
These include:
- SRS Verification Plan
- Design Verification Plan
- VnVPlan Verification Plan
- Code Walkthroughs mentioned in the Implementation Verification Plan
- Software Validation Plan

For completeness it would be best to include the results of these plans as there were outlined in the VnVPlan. This can be done by including a section that points to evidence of the results of these plans. For example, pointing to GitHub issues of team meetings, etc.

**Deadline**
April 4

**Estimated Work Hours**
4 hrs

**Comment by ethanlucask** [comment]
Not an issue. Documentation verification plans are okay as is.
