### ISSUE TITLE
Team #2 Review (VnVReport): Presentation of Usability testing data could be improved

### ISSUE THREAD

**Issue by Haxerus** [SammyG7/Mac-AR#234]
@samm82

**Summary**
Only the average scores from the usability testing data are presented. The presentation of the data could be improved by showing the data in other ways. For example, a histogram would better show the distribution of the responses.

The raw data obtained from the survey could also be included so that readers may perform their own analysis on the data.

**Deadline**
April 4

**Estimated Work Hours**
1 hr

**Comment by MatthewCollard** [comment]
Completed in commit id: 568eaf36bff32562880f71833df3a7b0f09f68a8
