### ISSUE TITLE
Team #2 Review (VnV Report): Insufficient Usability Testing Data

### ISSUE THREAD

**Issue by beatlepie** [SammyG7/Mac-AR#236]
@samm82

**Summary**
The usability testing data only shows the averaged answers of the questions, and no further reports. The VnVPlan specifies that there should be at least 20 people who tested, but it is unclear if this was fulfilled. In addition, it is unclear if these tests found satisfactory results or required more user input besides the 3/5 outlined for Test-UH8. 
![image](https://github.com/SammyG7/Mac-AR/assets/46289372/8ee96603-273d-4e44-98e8-c307692091f3)

**Deadline**
April 4th

**Estimated Work Hours**
2hr

**Comment by MatthewCollard** [comment]
Resolved in commit id: 568eaf36bff32562880f71833df3a7b0f09f68a8
