### ISSUE TITLE
Team #2 Review (VnV Plan): Some Abbreviations missing from the table

### ISSUE THREAD

**Issue by qw33ha** [SammyG7/Mac-AR#237]
@samm82

**Summary**
The Abbreviations section (section 2) refer to the one in VnV Plan or SRS if that's a repetitive work -- in that case SRS Abbreviation Table needs some update to include new Abbreviations like CI/CD, Vivox, NUnit, etc. 
![image](https://github.com/SammyG7/Mac-AR/assets/83600619/2e0494d3-43c6-49d8-bd0a-5d3fd235be4a)
![image](https://github.com/SammyG7/Mac-AR/assets/83600619/60d7729d-ea4e-4c43-92cb-b059ec8a1695)

**Deadline** April 4

**Estimated Work Hours** 10 min

**Comment by kierangara** [comment]
Resolved with commit 40618c3d2cdf62a81c8c92ecf348385ccf745df1
