### ISSUE TITLE
Team #2 Review (VnV Report): Inconsistancy between VnVPlan and VnVReport

### ISSUE THREAD

**Issue by beatlepie** [SammyG7/Mac-AR#238]
@samm82

**Summary**
![image](https://github.com/SammyG7/Mac-AR/assets/46289372/ca31328f-f3dd-495b-b0ab-978fe1b51118)
The input column is different from the VnVPlan. It is unclear what exactly these tests are for due to the generic name as well. This inconsistency seems to indicate that there was some kind of change between VnVPlan and VnVReport, but it is unclear what changed.

**Deadline**
April 4th

**Estimated Work Hours**
30min

**Comment by MatthewCollard** [comment]
![Image](https://github.com/SammyG7/Mac-AR/assets/102780755/2f94e835-8537-415a-993a-f9b2d8989cc8)



![Image](https://github.com/SammyG7/Mac-AR/assets/102780755/42af6294-00a7-425f-8589-342ef40218ec)



These screenshots are from our VnVPlan, the inputs are similar enough that the reader should not be confused, they can cross reference with the Id listed.  The inputs and outputs do match in terms of the keywords "Simple" and "Complex
