### ISSUE TITLE
Team 18 SRS Review: Use case diagram is not clearly readable

### ISSUE THREAD

**Issue by marischan888** [SammyG7/Mac-AR#24]
In the submitted assignment, the use case diagram lacks the necessary labels and captions, which are essential for clarity and understanding. The font and the size of the diagram title are also not consistent with the rest of the document. Refer to the following screenshot.
<img width="592" alt="Screenshot 2023-10-09 at 23 12 13" src="https://github.com/SammyG7/Mac-AR/assets/77364176/205025f7-6198-45f2-b8aa-1820703278b1">

Please ensure that figures and tables are clearly readable and of sufficient resolution is crucial. Not only does it enhance the reader's comprehension, but it also adds to the overall professionalism and credibility of the document. 

Team 18 TA: @CSchank

**Comment by MatthewCollard** [comment]
Resolved in commit id: 1fb20e82fa1c5c535b20c4013b1639b95cb585cf
