### ISSUE TITLE
Team2 Review: Context of the work diagram format

### ISSUE THREAD

**Issue by qw33ha** [SammyG7/Mac-AR#25]
---
@samm82 
Name: Team 2 Review
About: The context diagram in section 2.1.1 Context of the work has a wrong format

---

## Summary
- The context diagram claims to illustrate the interaction between external systems and this system, but it is actually a UML use case diagram. This diagram mainly focuses on the interaction between the system and its users. So this diagram needs to be remade with a new template. The most obvious external system/service interacting with the system is a database. Though a database can be considered a part of the application, it can still be treated as an external service in this section for the purpose of demonstration. An example can be found [here](https://github.com/arkinmodi/project-sayyara/blob/main/docs/SRS/diagrams/ContextOfWork.png)
-  The use case diagram itself has some relationships that do not make too much sense. For example, the 'start game' use case should not include 'interact with puzzle'. 'start game' sounds like the very beginning phase of the game, 'play game' may be a good option. Also, even when the user plays the game, solving puzzles is not mandatory for the base use case so includes may not be a proper relationship here (users can just do nothing in the game). 
Other relationships I'm not sure are:

1. 'join game' includes 'exit room'
2. 'send message' includes 'read message'
3. 'interact with puzzle' includes 'request hint'

Some of the use cases are optional for their base use cases, **_extends_** may be a better option, e.g. request hint **_extends_** interact with puzzle

## Deadline
- 23/10/2023

## Estimated Work Hours
- 1 hr

**Comment by ethanlucask** [comment]
This is not an issue. Use case diagram makes sense.
