### ISSUE TITLE
Team2 Review: Ambiguous Functional Requirement

### ISSUE THREAD

**Issue by millem42** [SammyG7/Mac-AR#26]
Requirement CG3 in section 2.2.1 reads: "The system shall allow the user to set the size of the game room." It is not made clear what determines the "size" of the game room (e.g. number of players, length of game, etc.). It is also not made clear in the rationale what makes a game smaller or bigger.

![image](https://github.com/SammyG7/Mac-AR/assets/98553968/6e879fca-fa77-44f6-a27e-00a8e4d7001e)

@samm82

**Comment by ethanlucask** [comment]
Completed in commit ID: d9d136da73141de01d320198e16eb7254ec3ecda
