### ISSUE TITLE
Team2 Review: Potential Risks with DB

### ISSUE THREAD

**Issue by qw33ha** [SammyG7/Mac-AR#27]
---
@samm82 
Name: Team 2 Review
About: Missing risks with database in section 5.1 Risks
<img width="700" alt="Screen Shot 2023-10-11 at 7 56 03 AM" src="https://github.com/SammyG7/Mac-AR/assets/83600619/bdeffcb1-91a9-4bc9-8c65-6209ca8de666">

---

## Summary
- Since the game includes functions like save and load games, it should store the game information and user information somewhere in the backend. If the database is included in the design, potential risks like data branch and data loss should be considered.

## Deadline
- 23/10/2023

## Estimated Work Hours
- 20 min

**Comment by ethanlucask** [comment]
Completed in commit ID: d9d136da73141de01d320198e16eb7254ec3ecda
