### ISSUE TITLE
Team 18 SRS Review: Missing content to describe likely/unlikely changes

### ISSUE THREAD

**Issue by qstommyshu** [SammyG7/Mac-AR#28]
The SRS document is missing a section describing requirements that are likely/unlikely to change, the keyword "LC" is only defined to "Likely Changes" but not used anywhere in the document. And this is an requirement in the SRS rubric.
![image](https://github.com/SammyG7/Mac-AR/assets/56746466/94474e03-405c-4321-b74c-d790485338a7)
SRS rubric:
![image](https://github.com/SammyG7/Mac-AR/assets/56746466/a637b2d3-4b6c-4537-a823-998f70703e6c)

Team 18 TA: @CSchank

**Comment by kierangara** [comment]
Resolved with commit 4400ead1c358e49213175c065f10d50a019b377e
