### ISSUE TITLE
TA Review (VnV Report): Test-PI2 should be explicitly performed for each puzzle

### ISSUE THREAD

**Issue by kierangara** [SammyG7/Mac-AR#282]
@samm82

**Summary**
Test-PI2 should be explicitly performed (and recorded) separately for each puzzle type. Likewise, specific data for w and h should be recorded in your Test-LF1 results.
**Deadline**
Apr 4, 2024
**Estimated Work Hours**
0.5

**Comment by MatthewCollard** [comment]
Resolved in commit id: 7816f8d78c5fdf4cad638111e6ca798380690567
