### ISSUE TITLE
TA Review (VnV Report): Formatting and spelling issues

### ISSUE THREAD

**Issue by kierangara** [SammyG7/Mac-AR#283]
@samm82

**Summary**
Minor formatting issues (e.g., extra horizontal lines in LaTeX tables, inconsistent capitalization, LaTeX quotation marks) and spelling (e.g., it should be "iPhone", "iOS", and "walkthrough" or "walk-through"). "TBD" should be explained, either generally or on a case-by-case basis (like in Test-UH6).
**Deadline**
Apr 4, 2024
**Estimated Work Hours**
1.0

**Comment by MatthewCollard** [comment]
Completed in commit id: [48154ac](https://github.com/SammyG7/Mac-AR/commit/48154ac548af3fd8a7509283565242cab2f1d720)
