### ISSUE TITLE
TA Review (VnV Report): "I feel creative" questionnaire question missing from report

### ISSUE THREAD

**Issue by kierangara** [SammyG7/Mac-AR#284]
@samm82

**Summary**
The "I feel creative while playing the game" question from the usability survey is missing in the VnV Report.
**Deadline**
Apr 4, 2024
**Estimated Work Hours**
0.25

**Comment by MatthewCollard** [comment]
Resolved in commit id: 393cab44f4a5f9cfc0d62fc0ece52418fbb13ae7
