### ISSUE TITLE
TA Review (VnV Report): No analysis performed on data collected related to usability testing

### ISSUE THREAD

**Issue by kierangara** [SammyG7/Mac-AR#285]
@samm82

**Summary**
No analysis performed on data collected related to usability testing; averages are simply listed. Specific data is not explicitly referenced for Test-UH4-5, especially considering the demographic.

How would these results interact with Test-HS1?
**Deadline**
Apr 4, 2024
**Estimated Work Hours**
1.0

**Comment by MatthewCollard** [comment]
Resolved in commit id: 568eaf36bff32562880f71833df3a7b0f09f68a8
