### ISSUE TITLE
TA Review (VnV Report): No specific data for Test-PR1-3

### ISSUE THREAD

**Issue by kierangara** [SammyG7/Mac-AR#286]
@samm82

**Summary**
Specific data should be included to support your claims for Test-PR1-3.
**Deadline**
Apr 4, 2024
**Estimated Work Hours**
0.5

**Comment by MatthewCollard** [comment]
Completed in commit id: [1815be0](https://github.com/SammyG7/Mac-AR/commit/1815be0be7278d746feb0a2b7161aaaf6c9d1b8f)
