### ISSUE TITLE
TA Review (VnV Report): Lackluster non-functional requirement testing

### ISSUE THREAD

**Issue by kierangara** [SammyG7/Mac-AR#287]
@samm82

**Summary**
Testing of other nonfunctional requirements is pretty lackluster - one test case isn't really a lot to verify an entire category of software quality
**Deadline**
Apr 4, 2024
**Estimated Work Hours**
1.0

**Comment by MatthewCollard** [comment]
Completed in commit id: fd684242dc1584248227078c482b651bbb1c9a8c
