### ISSUE TITLE
TA Review (VnV Report): Inconsistency in changes to report

### ISSUE THREAD

**Issue by kierangara** [SammyG7/Mac-AR#288]
@samm82

**Summary**
If FR-ST3 was removed, it should also be removed from Table 20. No test cases added for "password pop-up notifications" or "join lobby button disabling".

I'll give you the benefit of the doubt that you had none, but if any test cases failed initially, prompting action on your end, this information should be recorded here.
**Deadline**
Apr 4, 2024
**Estimated Work Hours**
1.0

**Comment by MatthewCollard** [comment]
Completed in commit id: fd684242dc1584248227078c482b651bbb1c9a8c
