### ISSUE TITLE
TA Review (VnV Report): No justification for questionnaire target

### ISSUE THREAD

**Issue by kierangara** [SammyG7/Mac-AR#289]
@samm82

**Summary**
Very little justification given for why the target of 3/5 was chosen, or why these specific metrics were selected.
**Deadline**
Apr 4, 2024
**Estimated Work Hours**
0.25 hrs

**Comment by MatthewCollard** [comment]
Resolved in commit id: 568eaf36bff32562880f71833df3a7b0f09f68a8
