### ISSUE TITLE
Team 18 SRS Review: Ambiguous words without explanation

### ISSUE THREAD

**Issue by qstommyshu** [SammyG7/Mac-AR#29]
There are some words used in the document that are a little ambiguous in the SRS document. 
Ambiguous wording violates two section in the SRS rubric:
1. ***Terms*** and acronyms needs to be defined before first use.
2. Requirements wording needs to be clear and precise, not ambiguous.

The Naming Conventions and Terminology section only defined acrynoms, didn't define terminologies used in other sections.
<img width="442" alt="image" src="https://github.com/SammyG7/Mac-AR/assets/56746466/05ca3302-1f30-4a60-8d0d-a9af387148b9">

Here are some examples of terminology seems ambiguous and should be defined before using:
1. assets. This word is being used in ST2 and 3.8 Legal Requirements, but the meaning of assets is ambiguous and not explained.
![image](https://github.com/SammyG7/Mac-AR/assets/56746466/0162baa2-72c5-4833-91f0-864ae81e4b50)

2. puzzle state. The word "puzzle state" is being referred in multiple times(only two examples are shown) in the document, but the meaning is ambiguous. What exactly is a "puzzle state"? Does the word "puzzle state" has the same meaning as "game state"? If they are, the SRS should only use either "puzzle state" or "game state" to avoid confusion, or an explanation should be provided in the document.
![image](https://github.com/SammyG7/Mac-AR/assets/56746466/4ece33d3-8265-4ef1-82b3-5a770a4e8863)
![image](https://github.com/SammyG7/Mac-AR/assets/56746466/02c12375-1149-4d1c-bffe-fd7db7901816)

3. room progress. The word "room progress" is being referred multiple times in the document, but the meaning is ambiguous. What's the differences between "overall room progress" and "progress on all puzzles" in SG2? An explanation should be provided in the document.
![image](https://github.com/SammyG7/Mac-AR/assets/56746466/29daa34c-ddd5-44a6-9c29-3bf9527a888e)

Team 18 TA: @CSchank

**Comment by kierangara** [comment]
Resolved with commit 7e9c390a920f99fbdc0b42334c480a19d3d940c8
