### ISSUE TITLE
Team2 Review: Lack of detail in Stakeholders

### ISSUE THREAD

**Issue by abh1nh** [SammyG7/Mac-AR#30]
@samm82 
![image](https://github.com/SammyG7/Mac-AR/assets/93843390/c8737cca-0673-4e76-bcb2-35fe337c254f)

It is not clear which subsection "The Users" is referring to within the template. It should be clearly labelled based on if it is referring to the customers or the hands-on users of the product. If it is the latter, it should ideally be put into the format as described in the template:
![image](https://github.com/SammyG7/Mac-AR/assets/93843390/32520abc-4fd3-486c-aacd-743c9e82ddd6)

There should also be explanations for missing subsections as for why they were left out. There are arguments that can be made for including certain subsections. For example, since there is only one type of user that has been mentioned, it might be sensible to give examples of Personas to further explain how different users with different backgrounds etc. might interact with Mac-AR. User participation is also another important section where it could be described how much time you expect the users to spend with your product and what type of information you expect them to provide, to determine the complete requirements.

**Comment by kierangara** [comment]
Resolved with commit d9d136da73141de01d320198e16eb7254ec3ecda. Second part of issue ignored as it assumes we used the template group 2 used when we did not. The template we used is correctly sited within our SRS.
