### ISSUE TITLE
Team2 Review: Operational and Environmental Requirements are too Broad

### ISSUE THREAD

**Issue by beatlepie** [SammyG7/Mac-AR#31]
@samm82
Name: Team 2 Review
About: Operational and Environmental Requirements too large
![image](https://github.com/SammyG7/Mac-AR/assets/46289372/0a24c7a8-916c-460d-9651-846c379bb169)
### Summary

This is an extremely broad scope. This seems to suggest that it will support all versions including the ones that are not getting regular updates. This could lead to significant complications in development and security concerns.

Looking up supported versions and checking what OS versions other XR applications are supporting may help narrow down the scope and improve supportability and maintenance work required in the long term.

### Deadline

* 23/10/2023

### Estimated Work Hours

* 1 hour

**Comment by ethanlucask** [comment]
Completed in commit ID: d9d136da73141de01d320198e16eb7254ec3ecda
