### ISSUE TITLE
Team2 Review: Fit Criterion not appropriate for solution constraint

### ISSUE THREAD

**Issue by Haxerus** [SammyG7/Mac-AR#32]
@samm82 
Name: Team2 Review
About: Fit criterion does not appropriately test the mandated constraint
![image](https://github.com/SammyG7/Mac-AR/assets/12162897/0f56f8e2-12e3-41c9-a19b-70c88c2d5bfb)

### Summary
The fit criterion "The product shall be written using Unity Engine" does not measure or test the constraint of the app needing to be a mobile application. Unity can be used to create non-mobile applications after all. Indicating that the app will be built as an installable application package (APK, etc.) or be otherwise accessible on mobile platforms would be more appropriate.

### Deadline
- 23/10/2023

### Estimated Work Hours
- 0.5 hours

**Comment by ethanlucask** [comment]
Completed in commit ID: d9d136da73141de01d320198e16eb7254ec3ecda
