### ISSUE TITLE
Team2 Review: Add rationales to safety and security requirements

### ISSUE THREAD

**Issue by millem42** [SammyG7/Mac-AR#36]
@samm82 
Name: Team 2 Review
About: Safety and security requirements have no rationales

**Summary**
The safety and security requirements listed in the hazard analysis have no rationales associated with them.

**Deadline**
23/10/2023

**Estimated Work Hours**
1 hour

**Comment by ethanlucask** [comment]
Fit criterion is present for the safety and security requirements. In the SRS, we had rationale only for functional requirements; the NFR's had fit criterion. No additional rationale is required in the rubric for them. Therefore this is not an issue.
