### ISSUE TITLE
Team 2 Review (Hazard Analysis): Missing failures related to user accounts 

### ISSUE THREAD

**Issue by qw33ha** [SammyG7/Mac-AR#37]
@samm82
Name: Team 2 Review
About: Missing failures related to user accounts 

Summary
The FMEA table is supposed to describe common hazards that may occur when using the application. However, a potential hazard with user accounts is missed from the table. Users may lose their accounts when the server crashes. The corresponding sections should either be added to the FMEA table or there should be an assumption about the account management system.

Deadline
02/05/2024

Estimated Work Hours
0.5 hour

**Comment by ethanlucask** [comment]
Users will not have accounts for the Mac-AR game. Similarly to games such as agar.io and snake.io, the user will enter a username at the start of each game session, and no account creation will be necessary. Therefore this is not an issue.
