### ISSUE TITLE
Team 18 HA Review: Grammar mistakes

### ISSUE THREAD

**Issue by qstommyshu** [SammyG7/Mac-AR#39]
Some sentences in the FMEA table end with a comma, some don't. 
The below screen shot shows some examples:
![image](https://github.com/SammyG7/Mac-AR/assets/56746466/1399ef2e-535a-402a-912a-a0e4595d52de)

Team 18 TA: @CSchank

**Comment by ethanlucask** [comment]
Resolved in commit ID: 174f9c28aa0dacd025db66c31ca675a6d1cc34d2
