### ISSUE TITLE
Team 18 HA Review: Missing 1 or more significant issues or several minor issues

### ISSUE THREAD

**Issue by jiaoa3** [SammyG7/Mac-AR#40]
Having an AR game as a mobile app could easily raise software version compatibility issues. 

What would the system do if two users had two apps with different versions? A sample requirement could be included such as: The system shall inform users to check for updates and use the latest version.

@CSchank

**Comment by ethanlucask** [comment]
Completed in commit ID: 3a32d6374ca85d4698d0d43779afaffacf3ac204
