### ISSUE TITLE
Team 18 HA Review: Requirement UH6 is irrelevant to hazard H4-1.

### ISSUE THREAD

**Issue by KehaoHuang** [SammyG7/Mac-AR#42]
In the causes of failure section of hazard H4-1, it is stated that the user leaves the pre-defined area set by calibration, implying that the hazard happens after the calibration setup period. However, the requirement UH6 describes the intended behaviour of the system during calibration setup. The requirement UH6 is not derived from the recommended action of the corresponding hazard(H4-1). According to the rubric, it is stated that to get an “exceeds” grade for the “Recommended Actions” section, there should be appropriately categorized and indication of proper elimination or mitigation strategy leading to safety requirements. Therefore, I think a more relevant requirement that’s led by the recommended action should be provided to ensure the system meets the intended behaviour.

![haz](https://github.com/SammyG7/Mac-AR/assets/77684152/b675e3ac-fa5b-4e07-be90-6f8a9f091cc4)

![req](https://github.com/SammyG7/Mac-AR/assets/77684152/c53bd0fc-26e6-4dd1-a6f2-0436562e3062)

@CSchank

**Comment by ethanlucask** [comment]
Resolved in commit ID: 174f9c28aa0dacd025db66c31ca675a6d1cc34d2
