### ISSUE TITLE
Team 18 HA Review: The UH4 Fit criterion is not directly related to the requirement.

### ISSUE THREAD

**Issue by qstommyshu** [SammyG7/Mac-AR#43]
The rubric mentioned the mitigation strategy should lead to the safety requirements. However, the fit criterion for UH4 is not directly related to the UH4 requirement itself.

The fit criterion for UH4 is exactly the same as the UH2 fit criterion, and it is not directly related to the UH4 requirement itself. The UH4 requirement emphasizes on “user re-enter an area with internet”, whereas the fit criterion emphasizes on “network connection is lost”. 

![image](https://github.com/SammyG7/Mac-AR/assets/56746466/79e2d176-570f-49b4-b0a1-f358ccd5c70f)

Team 18 TA: @CSchank

**Comment by ethanlucask** [comment]
Completed in commit ID: 905f3151621f611e4db16ad451e172fd86e7037d
