### ISSUE TITLE
Team 2 Review (Hazard Analysis): Missing failures related to backend server crashes

### ISSUE THREAD

**Issue by Haxerus** [SammyG7/Mac-AR#44]
@samm82 
Name: Team 2 Review
About: Missing failures related to backend server crashes.

### Summary
Client side application crashes are listed as a potential hazard. The Backend Server is also a part of the product being delivered and could also crash or terminate abruptly for similar reasons. It would be appropriate to list in the FMEA table the cause, effects and recommended actions in the event of a server crash.

### Deadline
02/05/2024

### Estimated Work Hours
1.5 hours

**Comment by ethanlucask** [comment]
Completed in commit ID: 92e5b693c7a20a373cf8f4e93e97c5d1ca95c87b
