### ISSUE TITLE
Team 2 HA Review: Missing Critical Assumption/Hazard

### ISSUE THREAD

**Issue by beatlepie** [SammyG7/Mac-AR#45]
@samm82
Name: Team 2 Review
About: Missing Critical Assumption/Hazard

Summary
The critical assumption does not mention whether the current user device has the necessary equipment or supported software versions to properly run the application.
Alternatively, the application could check for this issue and notify the user to update their software or connect the appropriate supporting device.

Deadline
23/10/2023

Estimated Work Hours
1 hour

**Comment by MatthewCollard** [comment]
The app store or google play store will not allow users to install the application if their device does not meet the specification, so this issue does not need to be considered by us, as we defined in our SRS what platforms we are intending to develop for, and what software versions the users will have.
