### ISSUE TITLE
Team 18 HA Review: Missing introduction/explanation to FMEA

### ISSUE THREAD

**Issue by yex33** [SammyG7/Mac-AR#46]
The section “5 Failure Mode and Effect Analysis” is missing an introduction or explanation to the hazard analysis method of choice. What is FMEA? What contents are included in a FMEA? This is especially needed when your FMEA Table is broken down into two separate tables. A sentence like “Table 2 and Table 3 in combination present the FMEA for the Mac AR application” or “Table 2 is continued in Table 3” would make this section more readable.

### Nit picks
- The caption should be unique for each table. Table 2 and Table 3 should not share the same caption: "FMEA Table"
- It would be better if you use [longtable](https://www.overleaf.com/learn/latex/Tables#Multi-page_tables) to properly format tables spanning multiple pages. That way you don't need to worry about the captions.
- Issue `\raggedright` in the table column specification to achieve the _left align_ instead of the default _justify_ horizontal alignment. That way there won't be lots of white spaces between words if the column is narrow.

Team 18 TA: @CSchank

**Comment by ethanlucask** [comment]
Closed with commit id: 905f3151621f611e4db16ad451e172fd86e7037d
