### ISSUE TITLE
Team 2 HA Review: Lack of detail in System Boundaries and Components

### ISSUE THREAD

**Issue by abh1nh** [SammyG7/Mac-AR#47]
@samm82 
Name: Team 2 Review
About: System Boundaries & Components

**Summary**
The Hazard Analysis document mentions the front-end as a component but not enough detail is provided on it. Front-end can be elaborated by further dividing it into components (if applicable) that interact with the back-end in different ways. System boundaries can also be elaborated on by explaining all user interactions with the system. Can break down "all the user's inputs" into things such as touch, movement inputs etc.

**Deadline**
23/10/2023

**Estimated Work Hours**
30 minutes

**Comment by ethanlucask** [comment]
The current description regarding system boundaries and components is in enough detail. The boundaries and components have been described in a broad sense which is allowed. Therefore this is not an issue that needs to be resolved.
