### ISSUE TITLE
Team 2 Review (Hazard Analysis): Users get injured is not a hazard

### ISSUE THREAD

**Issue by qw33ha** [SammyG7/Mac-AR#48]
@samm82
Name: Team 2 Review
About: Users get injured is not a hazard

Summary
The team has already mentioned in critical assumptions that the user will not intentionally get injured, and in the table there is still an entry called 'User is injured'. They can either remove the assumption or get rid of the failure in FMEA table.
Deadline
02/05/2024

Estimated Work Hours
15 mins

**Comment by ethanlucask** [comment]
User can still accidentally injure themself
