### ISSUE TITLE
Supervisor Meeting 1

### ISSUE THREAD

**Issue by SammyG7** [SammyG7/Mac-AR#5]
**Date**: Sept 19th, 2023

**Members**: Dr. Yuan, Sam, Ethan, Matthew, Kieran 

**Agenda**:
- Meet with supervisor to discuss what is expected out of this project
- Discuss stakeholders, scope, and expected features to prepare for requirements document
- Answer Dr. Yuan's questions about deadlines and deliverables

**Comment by kierangara** [comment]
Associated meeting minutes: https://github.com/SammyG7/Mac-AR/blob/main/docs/MeetingMinutes/MeetingMinutes.pdf
