### ISSUE TITLE
Team 2 Review (VnV Plan): Test needs more information

### ISSUE THREAD

**Issue by millem42** [SammyG7/Mac-AR#62]
![image](https://github.com/SammyG7/Mac-AR/assets/98553968/7e5add9a-551a-489f-ba74-9e780d46e8f3)

@samm82
Name: Team 2 Review
About: Test needs more information

Summary
Test-UH7 needs more information on how it will be performed. The test should specify how the connection becoming weaker will be simulated to cause the message to be displayed.

Deadline
02/05/2024

Estimated Work Hours
0.5 hours

**Comment by kierangara** [comment]
Completed in commit Id: c6091aadc47f5fb64c7491b167a6f22ce183d2dd
