### ISSUE TITLE
Team 2 VnV Plan Review: Operational and Environmental Requirements not fully tested

### ISSUE THREAD

**Issue by qw33ha** [SammyG7/Mac-AR#63]
@samm82
Name: Team 2 Review
About: Operational and Environmental Requirements not fully tested

Summary
Requirement OE-1 is only tested under the Look and Feel section without a specific OS version. The tests do not fulfill the requirements about compatible OS versions (Android 11 and above, iOS 16 or later)
<img width="714" alt="Screen Shot 2023-11-05 at 11 20 48 AM" src="https://github.com/SammyG7/Mac-AR/assets/83600619/f5267fb0-bdb6-4f77-956e-aff228b9c46f">
<img width="320" alt="Screen Shot 2023-11-05 at 11 24 39 AM" src="https://github.com/SammyG7/Mac-AR/assets/83600619/1b67fa10-cb0d-44fb-96b2-9e34471707a4">
<img width="348" alt="Screen Shot 2023-11-05 at 11 24 52 AM" src="https://github.com/SammyG7/Mac-AR/assets/83600619/247f94fe-09e3-4636-9581-26aa3ec5fd07">

Deadline
02/05/2024

Estimated Work Hours
0.5 hours

**Comment by MatthewCollard** [comment]
Completed in commit id: 1a044f11a9626e37ae388e5e74f4e33140ce6ab9
