### ISSUE TITLE
Team 2 VnV Plan Review: Arbitrary Division of the testing group

### ISSUE THREAD

**Issue by qw33ha** [SammyG7/Mac-AR#64]
@samm82
Name: Team 2 Review
About: Arbitrary Division of the testing group

Summary
- Performance Requirement PR2 requires the system available 24 hours a day, and in the test plan, it is divided into the day(6AM - 6 PM) and the night (6PM - 6AM) without further explanation. The team should explain why it is divided like this (e.g. on-peak and off-peak periods)
<img width="532" alt="Screen Shot 2023-11-05 at 11 35 22 AM" src="https://github.com/SammyG7/Mac-AR/assets/83600619/b968bf9f-820b-4688-a2a1-59d1ca73acea">

- Same for tests for UH3. The team divides the users into 3 groups by age: under 20, 20-30 and 30 and above. This division is arbitrary and needs more explanation based on user persona.
<img width="741" alt="Screen Shot 2023-11-05 at 11 35 56 AM" src="https://github.com/SammyG7/Mac-AR/assets/83600619/196379ba-344c-4629-8c40-942150c47f04">
<img width="462" alt="Screen Shot 2023-11-05 at 11 37 43 AM" src="https://github.com/SammyG7/Mac-AR/assets/83600619/1128b6bf-894a-49e6-a64f-694ceafc0835">
<img width="452" alt="Screen Shot 2023-11-05 at 11 37 56 AM" src="https://github.com/SammyG7/Mac-AR/assets/83600619/0e096f8b-d902-4d32-bb8d-9145d0fd5b69">

Deadline
02/05/2024

Estimated Work Hours
1 hours

**Comment by MatthewCollard** [comment]
Completed in commit id: dacc6456ef24377d09f64f9256da1db86764de1a
