### ISSUE TITLE
Team 18 VnV Review: Confusing initial state and input description for Test-CR3

### ISSUE THREAD

**Issue by qstommyshu** [SammyG7/Mac-AR#65]
The input description for Test-CR3 is confusing, "Nothing inputted for game room name" should not be considered as an input. While the meaning of this test case is understandable, I think the test case initial state and input can be rephrased into a more appropriate manner.

I think this modification can make the test case more clear:
Initial State: Nothing inputted for game room name.
Input: User tries to create a new game room

Reference:
![image](https://github.com/SammyG7/Mac-AR/assets/56746466/6522b216-a793-4907-981d-9b8a09512cc0)

Team 18 TA: @CSchank

**Comment by MatthewCollard** [comment]
Completed in commit id: 6ac9d3bed4e340bec1fab92498b0c3f954d82df4
