### ISSUE TITLE
Team 18 VnV Plan Review: 1 testing sample is not sufficient to represent the entire targeted age group

### ISSUE THREAD

**Issue by jiaoa3** [SammyG7/Mac-AR#66]
Using only one user as a sample in testing cases can be limiting and may not provide a comprehensive understanding of a system or application's performance. When testing a system or application, it's important to have a large set of users in test cases to account for variations in user behavior, preferences, and potential issues. 

![1](https://github.com/SammyG7/Mac-AR/assets/77683292/6364bf4c-5b12-4055-b80f-01e43c3d1b77)
![2](https://github.com/SammyG7/Mac-AR/assets/77683292/128f7ac1-fc04-4ca5-a14d-4eed7bef53d8)
![3](https://github.com/SammyG7/Mac-AR/assets/77683292/7429704d-7c4e-42a0-bc24-edd94e1cd3ca)
![4](https://github.com/SammyG7/Mac-AR/assets/77683292/bc3a3553-8602-41fb-a141-c5910cce01dc)

@CSchank

**Comment by MatthewCollard** [comment]
Completed in commit id: dacc6456ef24377d09f64f9256da1db86764de1a
