### ISSUE TITLE
Team 18 VnV Review: Game room capacity not verified.

### ISSUE THREAD

**Issue by KehaoHuang** [SammyG7/Mac-AR#67]
In the test case, it is mentioned that the game room is created with a certain capacity. However, according to the "How test will be performed" section, you will only verify the presence of the game room in the database without verifying the capacity of the game room is correct. In my opinion, you might consider taking a step further by verifying the game room capacity since it is asserted in the test case name.
![image](https://github.com/SammyG7/Mac-AR/assets/77684152/e1541d2c-8975-4493-8170-d03b487e2460)

@CSchank

**Comment by MatthewCollard** [comment]
Duplicate issue of #73, resolved in commit id: 32353134f0d2510e686b5b7487c71d690ee7dcba
