### ISSUE TITLE
Team 18 VnV Review: Repetitive Test case ID

### ISSUE THREAD

**Issue by qstommyshu** [SammyG7/Mac-AR#68]
Some of the test case ID are repetitive, but the case of the starting character is different. There is no explanation in the document addressing this scenario:
There exists Test-CR1,2,3 and a test-CR1,2,3 in the VnV plan document.

An example reference:
![image](https://github.com/SammyG7/Mac-AR/assets/56746466/e333b3e9-9d80-45e0-b15e-bc4789b53265)
![image](https://github.com/SammyG7/Mac-AR/assets/56746466/b7c4daed-5d39-4150-89ac-2c382eccc5ff)

Team 18 TA: @CSchank

**Comment by MatthewCollard** [comment]
Completed in commit id: 6c4fbfa31d352f57c42d7dc31d8704ddad8cc74b
