### ISSUE TITLE
Team 18 VnV Review: Ambiguous definitions of test type “functional” and “non-functional”

### ISSUE THREAD

**Issue by marischan888** [SammyG7/Mac-AR#69]
The definitions of test type “functional” and “non-functional” are unclear. They are also not present in either the “Symbols, Abbreviations, and Acronyms” section or the reference glossary section in the SRS.

A simple Google search for “functional” and “non-functional” testing led to [this webpage](https://community.microfocus.com/adtd/b/sws-alm/posts/types-of-software-testing-functional-non-functional). Under these definitions, functional tests are only for functional requirements while non-functional tests are for non-functional requirements.
test-UH9 (see attached screenshot below) is classified as a "functional" test case but targeted to test the NFR UH9.

On the other hand, if we use the definitions in relation to "structural testing" in [this webpage](https://artoftesting.com/structural-testing-vs-functional-testing#:~:text=Software%20testing%20is%20important%20to,implementation%20of%20the%20code%20structure.), tests like test-CR2 (screenshot attached below) clearly does not require any knowledge of the internal structure or the code base to be performed.

<img width="668" alt="Screenshot 2023-11-05 at 21 45 30" src="https://github.com/SammyG7/Mac-AR/assets/77364176/0873d54c-6299-45f8-a44c-4cae40267185">

@CSchank

**Comment by MatthewCollard** [comment]
Completed in commit id: 7a0e6536a87570d15f0534668ec9b1d1fdb47712
