### ISSUE TITLE
Team 18 VnV Review: Initial State and Input/Condition might not be N/A.

### ISSUE THREAD

**Issue by KehaoHuang** [SammyG7/Mac-AR#70]
In this test case, you wrote the initial state and input/condition as "N/A". After reading the "How test will be performed" section, it seems to me that the test case implies an initial state of "tester(s) running/using the application", and an input/condition of something like "various user interactions in the UI". 
![image](https://github.com/SammyG7/Mac-AR/assets/77684152/d3bc5389-cf8e-4976-9ab5-9714eb289213)

@CSchank

**Comment by MatthewCollard** [comment]
Completed in commit id: c7d486b80cf4bcc2d0b165fba7aab1472f1eba46
