### ISSUE TITLE
Team 18 VnV Review: Inconsistency in test cases formatting

### ISSUE THREAD

**Issue by qstommyshu** [SammyG7/Mac-AR#71]
The formatting of some test cases are inconsistent through out the document, the below example has multiple different fields and formatting:
1. {Name, followed by Id("i" in capital case, "d" in lower case), then followed by a space} vs {Name, followed by a space, followed by ID(both "i" and "d" are in capital case)}.
2. Test type are described as "Control" vs "Type", and the fields inside them are different.
3. "Input" vs "Input/Condition" and "Output" vs "Output/Result".
4. Test Case Derivation vs  nothing. 

References:
![image](https://github.com/SammyG7/Mac-AR/assets/56746466/108763db-0c88-4b6a-87a8-9ff6ba0c3d67)
![image](https://github.com/SammyG7/Mac-AR/assets/56746466/45841e13-bf2d-4174-9a6c-bee6f9f7b7a9)

**Comment by MatthewCollard** [comment]
Completed in commit id: 59b6df813c4e2efa4c253eaeab228141614588e2
