### ISSUE TITLE
Team 2 VnV Plan Review: Lack of detail in Software Validation Plan

### ISSUE THREAD

**Issue by abh1nh** [SammyG7/Mac-AR#72]
@samm82 
![image](https://github.com/SammyG7/Mac-AR/assets/93843390/6621ef27-30fb-4e16-b338-fd8ba323a92d)

The software validation plan section lists weekly meeting with the project supervisor, Dr. Irene Yuan as a way to validate the software which is a good starting point. However, Additional methods of software validation should be considered. For example, The group can use task-based inspection to test the software in different real world scenarios to help evaluate the functionality of the software. The group can also potentially consider bringing in other students as stakeholders so they could have them test out certain features of the application.

**Comment by MatthewCollard** [comment]
Completed in commit id: 7a0e6536a87570d15f0534668ec9b1d1fdb47712
