### ISSUE TITLE
Team 2 VnV Plan Review: Test-CR4 missing information

### ISSUE THREAD

**Issue by beatlepie** [SammyG7/Mac-AR#73]
@samm82
Name: Team 2 VnV Plan Review: Test-CR4 missing information 
About: Test-CR4 missing information 
![image](https://github.com/SammyG7/Mac-AR/assets/46289372/ba693866-3573-40b4-8c94-14da363a2598)

Summary
The test case derivation seems incomplete. This test seems possible to test automatically in an end to end test. The test should also verify the capacity of the game room, rather than simply checking the existence of the room in the database.

Deadline
02/05/2024

Estimated Work Hours
1 hours

**Comment by MatthewCollard** [comment]
Completed in commit id: 32353134f0d2510e686b5b7487c71d690ee7dcba
