### ISSUE TITLE
Team 2 VnV Plan Review: Spelling/Grammar mistakes in Test-PR1

### ISSUE THREAD

**Issue by Haxerus** [SammyG7/Mac-AR#74]
@samm82 
Name: Team 2 Review
About: Minor spelling and grammar mistakes in Performance Requirement Test-PR1

### Summary
![image](https://github.com/SammyG7/Mac-AR/assets/12162897/0fb9c851-1bf9-46b2-8dd3-9071ef44f1fc)
- The first part of the sentence appears to have duplicate instances of "a lobby". It could also be reworded to more clearly indicate the functionality being tested as a script that "calls a lobby" doesn't really make sense. Also, the word "timed" is misspelled as "times".

### Deadline
02/05/2024

### Estimated Work Hours
0.1 hour

**Comment by MatthewCollard** [comment]
Resolving in commit id: 8281858975412d7d6f41a3f5ac2d9f56ad85afa8
