### ISSUE TITLE
Team 2 VnV Plan Review: Tests CR-5 and CR-6 missing detail.

### ISSUE THREAD

**Issue by Haxerus** [SammyG7/Mac-AR#75]
@samm82
Name: Team 2 Review
About: Tests CR-5 and CR-6 missing detail in "How test will be performed" section.

### Summary
- The descriptions of how these two tests are performed are missing details on how the presence of a password will be determined. The cases mention that they will "verify the room is present in the database" which is fairly vague. It could be the case that a room is created with a password but the password field is not correctly set leaving the field blank on the database end. There would still be a room present in this case but the test would fail. The outputs are clear about the postcondition but the test performance steps should be updated to include details differentiating the two cases.

![image](https://github.com/SammyG7/Mac-AR/assets/12162897/6c064e81-2d8b-43fd-8647-693b8a4b878a)

### Deadline
02/05/2024

### Estimated Work Hours
0.5 hours

**Comment by MatthewCollard** [comment]
Completed in commit id: 17c3377382f934f9b3d69fb4ca2b2cd53a1bf60a
