### ISSUE TITLE
Clean Up Lobby Code

### ISSUE THREAD

**Issue by SammyG7** [SammyG7/Mac-AR#83]
**Summary**
There is some code in related to lobby creation that is inconsistent with our guidelines and should be cleaned up:
- Inconsistent function name syntax in PlayerList.cs (Ex. readyPress isn't PascalCase)
- Unused commented out code blocks (Ex. HandlePlayersStateChanged in PlayerList.cs )
- Dead code (Ex. The scene names in HostManager.cs don't match up with any existing scenes, and there is unused code related to a character select screen)

**Comment by MatthewCollard** [comment]
Completed in commit id:2d4451ce5ea096218b7c47485705da0dfdaa196f
