### ISSUE TITLE
CameraViewpointHandler is Empty

### ISSUE THREAD

**Issue by SammyG7** [SammyG7/Mac-AR#84]
**Summary**
CameraViewpointHandler consists of a class with a different name from the file, which itself has no functionality as all of its code is commented out. This script should be reviewed to check if it is still in use, and either cleaned up or deleted accordingly.

**Comment by MatthewCollard** [comment]
Completed in commit id: 309bba4e9d63a19c041ad64bac1d5f75d24a20f8
