### ISSUE TITLE
Edit Room Settings

### ISSUE THREAD

**Issue by MatthewCollard** [SammyG7/Mac-AR#97]
Due Date
Jan 8th

Priority
Medium

Description
Make it so user can edit the game room settings if they are the host

Associated Requirement

- [x] RS1
- [x] RS2
- [x] RS3
- [x] RS4
- [ ] RS5
- [x] RS6

**Comment by kierangara** [comment]
When creating room settings update setting requirements accordingly. TA feedback was meaning of settings was unclear, as to whether settings are just room capacity and password or if there are others as well. Specifically applies to RS1, RS2, RS6.
- [x] "Settings" in section 2.2.3 unclear

**Comment by MatthewCollard** [comment]
Completed RS1,RS2,RS3,RS4,RS6 in  commit id: 1f6166fcbc1f774ce8e7153920bc1a86367c4e52
RS5 is TBC
