### ISSUE TITLE
Save Game/Load Game

### ISSUE THREAD

**Issue by ethanlucask** [SammyG7/Mac-AR#98]
Due Date
Jan 8th

Priority
High

Description
Make it so user can save game session, as well as load game session

Associated Requirement
Save Game
- [ ] SG1
- [ ] SG2
- [ ] SG3
- [ ] SG4
- [ ] SG5
- [ ] SG6
- [ ] SG7
- [ ] SG8

Load Game
- [ ] LG1
- [ ] LG2
- [ ] LG3

**Comment by MatthewCollard** [comment]
No longer a requirement, does not need to be implemented
